server:
  port: 6549
  servlet.context-path: /auth

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
#    generate-ddl: true
    database: postgresql

  datasource:
    platform: postgres-playground
    url: jdbc:postgresql://localhost:7894/garbanzo
    username: richard
    password: richard
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  liquibase:
    enabled: true

security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: asdasdasdasdasd


user:
  oauth:
    clientId: R2dpxQ3vPrtfgF72
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: http://localhost:6549/login/oauth2/code/
  user:
    username: Richard
    password: abcd